name: 'Combine Dependabot PRs'
on:
  schedule:
  - cron: "0 0 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  combine-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: alphagov/github-action-combine-dependabot-prs/@v1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}